# -*- coding: utf-8 -*-
"""2024.09.04

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t7mAKLcP7LDSPXr3g6x4qq7pOlVMu5Zm
"""

print("Hello World!!")

print("Hello Python")

print("1,2,3,4,5")

import pylab as py

x_deg = py.arange(-180,180+1,)
x_rad = py.deg2rad(x_deg)
y = py.sin(x_rad)

py.plot(x_deg,y)

py.xlabel('x(deg)')
py.ylabel('sin(x)')
py.grid(True)